# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 이동형
title: Front-end Developer
email: leedhhhhh@gmail.com
website: www.github.com/leedhhhhh

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username: leedhhhhh
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
# icon: fas fa-globe
# url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile1.jpeg
about_content: | # this will include new lines to allow paragraphs
  안녕하세요. 프론트엔드 개발자 이동형입니다.

  TypeScript, React(Next.js), Vue(Nuxt.js) 기반의 프론트엔드를 주로 다루며 최근에는 서비스 최적화 및 향상을 위하여 불필요한 재랜더링 최소화, 번들 사이즈 최적화 등 고객이 서비스를 원할하게 이용할 수 있도록 성능 개선 면에 집중하고 있습니다.

  사용자가 만족할 수 있는 제품을 만들고 비즈니스 성장에 기여하는 개발자가 되고 싶습니다.

content:
  # - title: Projects # Title for the section
  # layout: list # Type of content section (list/text)
  # content:
  #   - layout: top-middle
  #     title: Super awesome project
  #     link: github.com/sproogen
  #     # link_text: Project Website
  #     additional_links:
  #       - title: sproogen/modern-resume-theme
  #         icon: fab fa-github
  #         url: github.com/sproogen/modern-resume-theme
  #       # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #   icon: fab fa-github
  #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  # quote: >
  #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  # description: | # this will include new lines to allow paragraphs
  #   I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Keytalk AI
        link: https://www.keytalkai.com
        # link_text: boringcompany.com
        sub_title: Front-end Developer
        caption: 2024.01 ~ 2024.10
        # quote: >
        #   루이스 개발 (2024.01 ~ 2024.10)
        description: | # this will include new lines to allow paragraphs
          루이스 개발 (2024.01 ~ 2024. 10) 
          * Lewis 프로젝트 프론트엔드 리드 개발자로 환경 구축부터 개발, 배포까지 진행했으며, 해당 프로젝트 유지보수와 이후 해당 프로젝트의 프롬프트 관리 및 서비스 관리를 위한 프로젝트 백오피스까지 개발을 도맡아 진행
         
          - 프로젝트 환경 구축부터 배포까지 리드 개발
          - 프롬프트 관리 및 서비스 관리를 위한 프로젝트 백오피스 개발
          - WebSocket 을 사용하여 프롬프트 엔지니어링을 통한 스토리 생성 기능 개발
          - 스토리 저작권 소유를 위한 NFT 개발
          - 스토리에 걸맞는 음악을 AI로 생성해주는 백그라운드 뮤직 기능 개발(프론트엔드)
          - i18n 을 사용한 다국어 처리 개발
          - 사용기술: React, Next.js, Redux, Typescript, WebSocket, AWS (S3, Cognito, Amplify, Clout Front, Route 53), GIthub Actions, i18n

          프롬프트 어드민 페이지 개발 (2024.06 ~ 2024.07) 
          * 프롬프트 담당 관리자가 현재까지 엑셀을 활용해 프롬프트를 관리하는 것을 보고 직접 기획, 디자인, 배포까지 진행 개발한 프로젝트로서 담당자의 프롬프트 관리를 위한 백오피스 사이트 개발
          
          - 기획부터 디자인, 개발, 배포까지 담당
          - 크롤링 방지를 위해 AWS Cognito, Amplify를 활용한 회원가입 및 로그인 구현
          - 사용자가 프롬프트를 만들어보고 테스트(속도비교, 결과값) 하여 결과값들을 비교 할 수 있는 페이지 개발
          - 실제로 서비스에 사용하는 프롬프트를 반영하기 위해 프롬프트를 관리하는 담당자의 검수를 받아야 하는 프로세스 과정을 개발
          - 프롬프트를 어떻게 관리하여 어떻게 개선해왔고 어떻게 결과값을 도출했는지 한 눈에 볼 수 있는 히스토리 페이지 개발
          - 회사 상장에 필요한 기술평가 자료에 프롬프트 어드민 사용
          - 사용기술: React, Next.js, Redux, Typescript, AWS (S3, Cognito, Amplify, Clout Front, Route 53), GIthub Actions

          마이셀럽스 스타 (2024.01 ~ 2024.10)
          - 한달에 약 150~200만 트래픽이 발생하는 앱으로서 쿠팡광고, 구글ADS 등 여러 광고를 붙이는 작업 진행
          - 전반적으로 도맡아서 유지보수 (매주 배너 워딩 수정, 배너광고 수정, 모달광고 수정 등)
          - 사용기술: Vue2, Nuxt, Veux, Typescript, AWS (S3, Cognito, Amplify, Clout Front, Route 53), GIthub Actions

          스테이피아 (2024.01 ~ 2024.10)
          - 호텔 상세페이지에서 kayak을 통해 예약 할 수 있도록 기능개발
          - 전세계적으로 사용하는 호텔예약사이트로서 사용지 비중이 외국인이 높기때문에 다국어 기능 개발 및 유지보수
          - 사용기술: Vue2, Nuxt, Veux, Typescript, AWS (S3, Cognito, Amplify, Clout Front, Route 53), GIthub Actions

      - layout: left
        title: 투라인코드
        link: https://www.twolinecode.com
        # link_text: boringcompany.com
        sub_title: Front-end Developer
        caption: 2022.11 ~ 2023.10
        # quote: >
        #   루이스 개발 (2024.01 ~ 2024.10)
        description: | # this will include new lines to allow paragraphs
          TMAP 공항버스 운행 관리 시스템 개발/운영 (2022.11 ~ 2023. 02)
          - TMAP 공항버스 Admin 페이지 개발 (정시성, 일별탑승율, 월별탑승율 등)
          - Vue3와 Quasar를 이용한 UI 개발 및 상태 관리
          - REST API와 Axios를 활용한 API 통신
          - JWT를 사용한 로그인/회원가입 기능 구현
          - xlsx.js 라이브러리를 활용한 엑셀 업로드 및 추출 기능 개발
          - TMAP에서 제공하는 지도 오픈소스 api를 통해 공항버스의 실시간 위치를 지도에 표시해주는 기능 개발
          - 사용기술: Vue3, TypeScript, Quasar, Pinia, Axios, JWT, xlsx.js

          Snowflake 파트너십 PBS 상품 개발 (2023.02 ~ 2023.04)
          - Snowflake를 사용하는 업체별 관리 페이지 개발
          - Vue3와 Quasar를 이용한 UI 개발 및 상태 관리
          - Snowflake OAuth를 이용한 로그인 기능 구현
          - 사용기술: Vue3, TypeScript, Quasar, Pinia, Axios, Snowflake OAuth

          공항버스 승객 예약 서비스 개발 (2023.04 ~ 2023.07)
          - TMAP 공항버스 Admin 페이지의 승객 예약 관련 기능 개발 (매출 현황, 예약자 현황 등)
          - Vue3와 Quasar를 이용한 UI 개발 및 상태 관리
          - JWT를 사용한 로그인/회원가입 기능 구현
          - 사용기술: Vue3, TypeScript, Quasar, Pinia, Axios, JWT

          SK 브로드밴드 셋톱박스 관리 시스템 개발 (2023.09 ~ 2023.10)
          - SK 브로드밴드 셋톱박스 관리 시스템의 Admin 페이지 개발 및 수정
          - 사용기술: React, TypeScript, Axios, Style Component

      - layout: left
        title: 유니아이텍
        link: http://www.unique1.co.kr
        # link_text: boringcompany.com
        sub_title: Front-end Developer
        caption: 2021.07 ~ 2022.07
        # quote: >
        #   루이스 개발 (2024.01 ~ 2024.10)
        description: | # this will include new lines to allow paragraphs
          홈앤쇼핑 유지보수 (2021.07 ~ 2022. 10)
          - 상품 목록 페이지 유지보수 및 찜 기능 개발
          - 사용기술: JSP, Java Spring, MyBatis

          홈앤쇼핑 이데이잇츠 정기배송 프로젝트 (2021.10 ~ 2022.07)
          - 정기배송 장바구니 및 상품 상세 페이지 개발
          - 가변형 설문 개발 (MyBatis 사용)
          - 이니시스를 이용한 결제 기능 개발 (협업)
          - 사용기술: JSP, Java Spring, MyBatis

  # - title: Education # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       title: 동의대학교
  #       caption: 2010 - 2013
  #       sub_title: 광고홍보학과
  #       quote: >
  #         Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
  #       description: | # this will include new lines to allow paragraphs
  #         During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

  #         I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      언어
      - HTML5, CSS3, JavaScript, TypeScript

      프레임워크
      - React, Vue, Nextjs, Nuxtjs

      상태관리
      - Recoil, Redux, Pinia

      형상관리
      - Github, GitLab

      CSS
      - Style-component, Scss, Tailwind, Quasar

      협업툴
      - Jira, Slack, Git

      자격증
      - CKA (Certified Kubernetes Administrator)

      티스토리
      - https://leedhhhhh.tistory.com

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
